config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'

  resources :genres

  resources :games do
    member do
      put 'like' => 'games#like'
    end
  end

  post 'games/search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :genres
  has_one_attached :thumbnail
  has_rich_text :review
  acts_as_votable

  def resize_thumbnail
    thumbnail.variant(resize: "240x135!")
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter
  
  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_feature
  helper_method :is_admin!

  def set_feature
    @feature = Genre.where(feature_in_navbar: true).order('name ASC')
  end

  def is_admin!
    unless current_user&.admin
      redirect_to root_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :like]
  before_action :set_genre, except: [:show, :destroy]
  before_action :is_admin!, except: [:index, :show, :like]
  before_action :authenticate_user!, only: [:like]

  def index
    set_games_and_genre_with_criteria(params[:genre], params[:order])
  end

  def search
    set_games_and_genre_with_criteria(params[:genre], params[:order])
  end

  def show
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    if current_user.voted_for? @game
      @game.unliked_by current_user
    else
      @game.liked_by current_user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def set_genre
      @genres = Genre.all
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :review, :rating, :thumbnail, genre_ids: [])
    end

    def set_games_and_genre_with_criteria(requested_genre, requested_order)
    if requested_genre.nil? || requested_genre.eql?('All')
      games_by_genre = Game.all
      @genre_name = 'All'
    else
      games_by_genre = filter_games_by_genre(requested_genre)
      @genre_name = requested_genre
    end
    @order = requested_order
    order_games(requested_order, games_by_genre)
  end

  def filter_games_by_genre(genre_name)
    @genre = Genre.find_by(name: genre_name)
    games = if @genre.nil?
              Game.none
            else
              @genre.games
    end
  end

  def order_games(_order, _games)
    @games = case _order
             when 'A-Z'
               _games.order('title ASC')
             when 'Z-A'
               _games.order('title DESC')
             when 'Highest Rating First'
               _games.order('rating DESC')
             when 'Lowest Rating First'
               _games.order('rating ASC')
             when 'Newest First'
               _games.order('created_at DESC')
             when 'Oldest First'
               _games.order('created_at ASC')
             else
               _games.order('title ASC')
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :is_admin!
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @games = @genre.games
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name, :feature_in_navbar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.rich_text_area :review %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :genres %>
    <%= form.collection_select :genre_ids, @genres, :id, :name, {}, {multiple: true} %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_genres.html.erb
<h1><%= link_to @genre_name, root_path %></h1>
<div id="games">
  <% @games.each do |game| %>
    <% if game.thumbnail.attached? %>
      <%= link_to image_tag(game.resize_thumbnail), game_path(game, genre: @genre_name, order: @order) %>
    <% else %>
      <div style="width: 240px; height: 135px">
        <%= link_to game.title, game %>
      </div>
    <% end %>
  <% end %>
</div>

<% @genres.each do |genre| %>
  <h1><%= genre.name %></h1>
  <% genre.games.each do |game| %>
    <h2><%= link_to image_tag(game.thumbnail, height: 200), game  %></h2>
  <% end %>
<% end %>

app/views/games/_like_link.html.erb
<% if current_user %>
  <% vote_text = current_user&.voted_for?(game) ? "Unlike" : "Like" %>
  <%= link_to vote_text, like_game_path(game), method: :put, remote: :true, class: 'link-post' %>
<% else %>
  <%= link_to 'Like', new_user_session_path, class: 'like-post' %>
<% end %>

app/views/games/_likes.html.erb
<%= pluralize(game.get_upvotes.size, 'Like') %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>
<div class="search-container">
    <%= form_tag(games_search_path, remote: true) do %>
    <div class="field">
      <%= label_tag :genre, "Genre: " %>

      <%= select_tag :genre, options_from_collection_for_select(
        @genres,
          :name,
          :name,
          "0"), {include_blank: 'All'}
       %>
       <%= label_tag :order, 'Game order' %>
       <%= select_tag :order, options_for_select(
         [
           "A-Z",
           "Z-A",
           "Highest rating first",
           "Lowest rating first",
           "Newest first",
           "Oldest first"
         ]), {include_blank: "Order"}
        %>
        <%= submit_tag 'Search' %>
      </div>
    <% end %>
</div>

<div id="genres">
  <%= render 'games/genres' %>
</div>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Review</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.review %></td>
        <td><%= game.rating %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/like.js.erb
$("#like-count").html("<%= j render 'games/likes', game: @game %>");
$("#like-link").html("<%= j render 'games/like_link', game: @game %>");

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/search.js.erb
var genres = document.getElementById("genres");
var games = document.getElementById("games");
window.history.replaceState(null, null, "?genre=<%= @genre_name %>?order=<%= @order %>");
genres.innerHTML = "<%= j render 'games/genres' %>";

app/views/games/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= image_tag(@game.thumbnail, class: 'img-fluid') if @game.thumbnail.attached? %>
      <div class="row">
        <div class="col-12">
          <h4>
            [<%= @game.rating %>/10]
          </h4>
        </div>
        <div class="col-12">
          <h5>
            <div id="like-count">
              <%= render 'games/likes', game: @game %>
            </div>
            <div id="like-link">
              <%= render 'games/like_link', game: @game %>
            </div>
            <hr />
          </h5>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <h6>
            This game belongs to <%= pluralize(@game.genres.count, 'Genre') %>
          </h6>
        </div>
        <% @game.genres.each do |genre| %>
          <div class="col-6">
            <%= link_to genre.name, root_path(genre: genre.name) %>
          </div>
        <% end %>
        <div class="col-12">
          <% if current_user&.admin %>
            <%= link_to 'Edit', edit_game_path(@game), class: 'btn btn-warning' %>
            <%= link_to 'Delete', @game, method: :delete, data: {confirm: 'Are you sure you want to delete this game?'}, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <h1>
        <% if params[:genre].nil? %>
          <%= link_to @game.title, root_path %>
        <% else %>
          <%= link_to @game.title, root_path(genre: params[:genre], order: params[:order]) %>
        <% end %>
      </h1>
      <div class="container">
        <%= @game.review %>
      </div>
    </div>
  </div>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :feature_in_navbar %>
    <%= form.check_box :feature_in_navbar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<div class="container">
  <h1 style="text-alingn: center">
    <%= link_to 'Genres', root_path %>
  </h1>

  <% @genres.each do |genre| %>
    <div class="container">
      <div class="row">
        <%= form_with(model: genre, local: true) do |form| %>
          <div class="col">
            <div class="form-group row">
              <div class="col">
                <%= form.text_field :name, class: 'form-control' %>
              </div>
              <div class="col-form-label">
                <%= form.label "Feature", class: 'col-form-label' %>
              </div>
              <div class="col">
                <%= form.check_box :feature_in_navbar, class: 'form-control' %>
              </div>
              <div class="col">
                <%= form.submit 'Update' %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="col">
          <%= link_to 'Destroy', genre, method: :delete, data: {confirm: 'Are you sure you want to delete the entire genre?'}, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <% @games.each do |game| %>
    <p><%= game.title %></p>    
  <% end %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Game review', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% @feature.each do |genre| %>
        <li class="nav-item">
          <%= link_to genre.name, root_path(genre: genre.name), class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to 'Account settings', edit_user_registration_path, class: 'dropdown-item' %>
            <% if current_user.admin %>
              <%= link_to 'New game review', new_game_path, class: 'dropdown-item' %>
              <%= link_to 'New genre', new_genre_path, class: 'dropdown-item' %>
              <%= link_to 'Manage genres', genres_path, class: 'dropdown-item' %>
            <% end %>
            <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>